cask "font-commit-mono" do
  version "1.143"
  sha256 "1fc82759611ebfe365d4d075f9573625f348fc4dd228c97487764c9ac861996e"

  url "https://github.com/yofriadi/homebrew-tap/releases/download/commit-mono-v#{version}/CommitMono-all-v#{version}.zip"
  name "Commit Mono"
  homepage "https://commitmono.com/"

  livecheck do
    url "https://github.com/eigilnikolajsen/commit-mono/releases"
    strategy :github_latest
  end

  font "CommitMono-200-Italic.otf"
  font "CommitMono-200-Regular.otf"
  font "CommitMono-225-Italic.otf"
  font "CommitMono-225-Regular.otf"
  font "CommitMono-250-Italic.otf"
  font "CommitMono-250-Regular.otf"
  font "CommitMono-275-Italic.otf"
  font "CommitMono-275-Regular.otf"
  font "CommitMono-300-Italic.otf"
  font "CommitMono-300-Regular.otf"
  font "CommitMono-325-Italic.otf"
  font "CommitMono-325-Regular.otf"
  font "CommitMono-350-Italic.otf"
  font "CommitMono-350-Regular.otf"
  font "CommitMono-375-Italic.otf"
  font "CommitMono-375-Regular.otf"
  font "CommitMono-400-Italic.otf"
  font "CommitMono-400-Regular.otf"
  font "CommitMono-425-Italic.otf"
  font "CommitMono-425-Regular.otf"
  font "CommitMono-450-Italic.otf"
  font "CommitMono-450-Regular.otf"
  font "CommitMono-475-Italic.otf"
  font "CommitMono-475-Regular.otf"
  font "CommitMono-500-Italic.otf"
  font "CommitMono-500-Regular.otf"
  font "CommitMono-525-Italic.otf"
  font "CommitMono-525-Regular.otf"
  font "CommitMono-550-Italic.otf"
  font "CommitMono-550-Regular.otf"
  font "CommitMono-575-Italic.otf"
  font "CommitMono-575-Regular.otf"
  font "CommitMono-600-Italic.otf"
  font "CommitMono-600-Regular.otf"
  font "CommitMono-625-Italic.otf"
  font "CommitMono-625-Regular.otf"
  font "CommitMono-650-Italic.otf"
  font "CommitMono-650-Regular.otf"
  font "CommitMono-675-Italic.otf"
  font "CommitMono-675-Regular.otf"
  font "CommitMono-700-Italic.otf"
  font "CommitMono-700-Regular.otf"
  font "CommitMono-VF.ttf"

  # No zap stanza required
end
