cask "font-recursive-mono-nerd-font" do
  version "1.085"
  sha256 "b0480f1b92292062bb92012a082224fc18abe2e6787e97d03af1221c6f5f59da"

  url "https://github.com/yofriadi/homebrew-tap/releases/download/recursive-v#{version}/RecMonoNerdFont-v#{version}.tar.xz"
  name "Recursive Mono Nerd Font"
  desc "Variable-inspired programming font with all subfamilies and weights, patched with Nerd Font glyphs"
  homepage "https://www.recursive.design/"

  livecheck do
    url "https://api.github.com/repos/arrowtype/recursive/releases/latest"
    strategy :json do |json|
      json["tag_name"]&.sub(/^v/, "")
    end
  end

  font "RecMonoCasualNerdFontMono-Black.otf"
  font "RecMonoCasualNerdFontMono-BlackItalic.otf"
  font "RecMonoCasualNerdFontMono-Bold.otf"
  font "RecMonoCasualNerdFontMono-BoldItalic.otf"
  font "RecMonoCasualNerdFontMono-ExtraBlack.otf"
  font "RecMonoCasualNerdFontMono-ExtraBlackItalic.otf"
  font "RecMonoCasualNerdFontMono-ExtraBold.otf"
  font "RecMonoCasualNerdFontMono-ExtraBoldItalic.otf"
  font "RecMonoCasualNerdFontMono-Italic.otf"
  font "RecMonoCasualNerdFontMono-Light.otf"
  font "RecMonoCasualNerdFontMono-LightItalic.otf"
  font "RecMonoCasualNerdFontMono-Medium.otf"
  font "RecMonoCasualNerdFontMono-MediumItalic.otf"
  font "RecMonoCasualNerdFontMono-Regular.otf"
  font "RecMonoCasualNerdFontMono-SemiBold.otf"
  font "RecMonoCasualNerdFontMono-SemiBoldItalic.otf"
  font "RecMonoDuotoneNerdFontMono-Black.otf"
  font "RecMonoDuotoneNerdFontMono-BlackItalic.otf"
  font "RecMonoDuotoneNerdFontMono-Bold.otf"
  font "RecMonoDuotoneNerdFontMono-BoldItalic.otf"
  font "RecMonoDuotoneNerdFontMono-ExtraBlack.otf"
  font "RecMonoDuotoneNerdFontMono-ExtraBlackItalic.otf"
  font "RecMonoDuotoneNerdFontMono-ExtraBold.otf"
  font "RecMonoDuotoneNerdFontMono-ExtraBoldItalic.otf"
  font "RecMonoDuotoneNerdFontMono-Italic.otf"
  font "RecMonoDuotoneNerdFontMono-Light.otf"
  font "RecMonoDuotoneNerdFontMono-LightItalic.otf"
  font "RecMonoDuotoneNerdFontMono-Medium.otf"
  font "RecMonoDuotoneNerdFontMono-MediumItalic.otf"
  font "RecMonoDuotoneNerdFontMono-Regular.otf"
  font "RecMonoDuotoneNerdFontMono-SemiBold.otf"
  font "RecMonoDuotoneNerdFontMono-SemiBoldItalic.otf"
  font "RecMonoLinearNerdFontMono-Black.otf"
  font "RecMonoLinearNerdFontMono-BlackItalic.otf"
  font "RecMonoLinearNerdFontMono-Bold.otf"
  font "RecMonoLinearNerdFontMono-BoldItalic.otf"
  font "RecMonoLinearNerdFontMono-ExtraBlack.otf"
  font "RecMonoLinearNerdFontMono-ExtraBlackItalic.otf"
  font "RecMonoLinearNerdFontMono-ExtraBold.otf"
  font "RecMonoLinearNerdFontMono-ExtraBoldItalic.otf"
  font "RecMonoLinearNerdFontMono-Italic.otf"
  font "RecMonoLinearNerdFontMono-Light.otf"
  font "RecMonoLinearNerdFontMono-LightItalic.otf"
  font "RecMonoLinearNerdFontMono-Medium.otf"
  font "RecMonoLinearNerdFontMono-MediumItalic.otf"
  font "RecMonoLinearNerdFontMono-Regular.otf"
  font "RecMonoLinearNerdFontMono-SemiBold.otf"
  font "RecMonoLinearNerdFontMono-SemiBoldItalic.otf"
  font "RecMonoSmCasualNerdFontMono-Black.otf"
  font "RecMonoSmCasualNerdFontMono-BlackItalic.otf"
  font "RecMonoSmCasualNerdFontMono-Bold.otf"
  font "RecMonoSmCasualNerdFontMono-BoldItalic.otf"
  font "RecMonoSmCasualNerdFontMono-ExtraBlack.otf"
  font "RecMonoSmCasualNerdFontMono-ExtraBlackItalic.otf"
  font "RecMonoSmCasualNerdFontMono-ExtraBold.otf"
  font "RecMonoSmCasualNerdFontMono-ExtraBoldItalic.otf"
  font "RecMonoSmCasualNerdFontMono-Italic.otf"
  font "RecMonoSmCasualNerdFontMono-Light.otf"
  font "RecMonoSmCasualNerdFontMono-LightItalic.otf"
  font "RecMonoSmCasualNerdFontMono-Medium.otf"
  font "RecMonoSmCasualNerdFontMono-MediumItalic.otf"
  font "RecMonoSmCasualNerdFontMono-Regular.otf"
  font "RecMonoSmCasualNerdFontMono-SemiBold.otf"
  font "RecMonoSmCasualNerdFontMono-SemiBoldItalic.otf"
end
